name: Run Reusable Test Workflow

on:
  workflow_call:
    inputs:
      bun-version:
        required: true
        type: string
    outputs:
      test_result_1:
        description: "The result of the E2E test run"
        value: ${{ jobs.test.outputs.test_result_1 }}
      test_result_2:
        description: "The result of the ID test run"
        value: ${{ jobs.test.outputs.test_result_2 }}
      test_result_3:
        description: "The result of the POST test run"
        value: ${{ jobs.test.outputs.test_result_3 }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test_result_1: ${{ steps.set-result.outputs.test_result_1 }}
      test_result_2: ${{ steps.set-result.outputs.test_result_2 }}
      test_result_3: ${{ steps.set-result.outputs.test_result_3 }}
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ‘¨â€ðŸ³ Setup Bun ${{ inputs.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: ðŸ“¦ Install dependencies
        run: bun install

      - name: ðŸ§ª Run E2E tests
        id: smoke-test-1
        run: bun test e2e.test.ts

      - name: ðŸ§ª Run ID tests
        id: smoke-test-2
        run: bun test id.test.ts

      - name: ðŸ§ª Run POST tests
        id: smoke-test-3
        run: bun test post.test.ts

      - name: ðŸ“¤ Set result output
        id: set-result
        run: |
          echo "test_result_1=${{ steps.smoke-test-1.outcome }}" >> $GITHUB_OUTPUT
          echo "test_result_2=${{ steps.smoke-test-2.outcome }}" >> $GITHUB_OUTPUT
          echo "test_result_3=${{ steps.smoke-test-3.outcome }}" >> $GITHUB_OUTPUT
